"""Add nationality to Player

Revision ID: 4131350a944e
Revises: f196289ff507
Create Date: 2026-08-12 09:22:02.813847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4131350a944e'
down_revision = 'f196289ff507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
