"""Add detailed player match statistics

Revision ID: b2b697778026
Revises: 29b468914bd1
Create Date: 2026-08-12 17:10:56.291948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b697778026'
down_revision = '29b468914bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals_conceded', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('passes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pass_accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tackles', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('interceptions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('clearances', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('blocks', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fouls', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('offsides', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_column('offsides')
        batch_op.drop_column('fouls')
        batch_op.drop_column('blocks')
        batch_op.drop_column('clearances')
        batch_op.drop_column('interceptions')
        batch_op.drop_column('tackles')
        batch_op.drop_column('pass_accuracy')
        batch_op.drop_column('passes')
        batch_op.drop_column('goals_conceded')

    # ### end Alembic commands ###
