"""Add lineup and lineup player models

Revision ID: f196289ff507
Revises: 72cd203c7d4d
Create Date: 2026-08-12 07:16:09.142999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f196289ff507'
down_revision = '72cd203c7d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineup_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('starter', sa.Boolean(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineup_players')
    op.drop_table('lineups')
    # ### end Alembic commands ###
