"""Add match events

Revision ID: f3d5d3b53a95
Revises: b2b697778026
Create Date: 2026-08-13 20:05:46.620712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d5d3b53a95'
down_revision = 'b2b697778026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('assist_player_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('added_time', sa.Integer(), nullable=True),
    sa.Column('substitution_in_player_id', sa.Integer(), nullable=True),
    sa.Column('substitution_out_player_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assist_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['substitution_in_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['substitution_out_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_events')
    # ### end Alembic commands ###
